spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/hogwarts_jaec
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

server.port=8080

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
